spring.application.name=DoorShop
spring.datasource.url=jdbc:postgresql://localhost:5432/doorshop
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=1111
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
server.port=4000